version: '3'

services:

  log4jq-demo:
    build: .
    command: >
      ./gradlew -Dorg.gradle.daemon=false --offline -Plog4jq_database=postgres demo
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
